# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Texlive.Texlive
PackageVersion: 2023
PackageLocale: en-US
Publisher: TeX Users Group
PublisherUrl: https://tug.org/index.html
PackageName: Tex Live
PackageUrl: https://tug.org/texlive/
License: Custom 
LicenseUrl: https://tug.org/texlive/LICENSE.TL
ShortDescription: A comprehensive cross-platform TeX distribution
ManifestType: defaultLocale
ManifestVersion: 1.4.0
